/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.fmlUi;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.text.ParseException;

import java.sql.Date;
import java.util.Calendar;

//used for timer
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

//does the sorting of the arraylist
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author termaat
 */
public class fmlUi extends javax.swing.JFrame {

    int lstInsertID = 0;
    int row_num = 0;
    int rec_id = 0;
    int monTracker = 0;
    int weekTracker = 8;

     ArrayList<Transaction> ledgerList = new ArrayList<Transaction>();
            // ArrayList of the Transaction object
            // the ledger/checkbook of the application
    
     //Transaction row;
            // not sure what this actually does, 
    
    SQLite sqlite = new SQLite();
            // created a new object to do db interaction
                    
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/YYYY");
    
    // date used globally to test against current date
    // should never change
    static java.util.Date today = new java.util.Date();
    java.sql.Date sqlToday = new java.sql.Date(today.getTime());
    String stringToday = sdf.format(sqlToday.getTime());
    
    // this it the sql future date used to get the 
    // forecasted balance
    String futureDate = "2525-01-01"; // YYYY-MM-DD
    String futureDatex = "01/01/2525";
    java.sql.Date sqlFutureDate = java.sql.Date.valueOf(futureDate);
    
    // sqlDate used to pass to various function of sqlite class
    // always changing based in user input
    java.sql.Date sqlDate = new java.sql.Date(today.getTime());
    //SimpleDateFormat sdf2 = new SimpleDateFormat("MM/dd/YYYY");
    
    FreakyDate Freaky = new FreakyDate();
    
    DefaultTableModel model;
    
    
    /**
     * Creates new form fmlUi
     */
    public fmlUi() {
        initComponents();
        model = (DefaultTableModel) tblLedger.getModel();
        rdoShowAll.setSelected(true);
        ListTransactions();
        rdoShowAll.setSelected(true);
        rdoByMonth.setSelected(false);
        rdoByWeek.setSelected(false);
        
        
        // see of the db is already set up
        // 0 means there is no table
        int isReady = sqlite.IsAcctSetup();
        if(isReady == 0){
            sqlite.createDB();
            sqlite.createTranTbl();
            displayMessage("Enter 1st transaction to set up Acct. balance");
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCurrentBal = new javax.swing.JLabel();
        lblForecastBal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLedger = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        rdoShowAll = new javax.swing.JRadioButton();
        rdoByMonth = new javax.swing.JRadioButton();
        rdoByWeek = new javax.swing.JRadioButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblForecastDate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtFormatDate = new javax.swing.JFormattedTextField();
        cbRepeater = new javax.swing.JCheckBox();
        rdoDelete = new javax.swing.JRadioButton();
        rdoUpdate = new javax.swing.JRadioButton();
        rdoClear = new javax.swing.JRadioButton();
        btnDoIt = new javax.swing.JButton();
        rdoDeposit = new javax.swing.JRadioButton();
        rdoExpense = new javax.swing.JRadioButton();
        lblDebug = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFirstDay = new javax.swing.JLabel();
        lblLastDay = new javax.swing.JLabel();
        JPanelPie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ledger", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Today...$");

        jLabel2.setText("|  Forecasted Balance as of");

        lblCurrentBal.setBackground(new java.awt.Color(102, 255, 102));
        lblCurrentBal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCurrentBal.setText("$1250");

        lblForecastBal.setText("$2125");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 200));
        jScrollPane2.setSize(new java.awt.Dimension(300, 200));

        tblLedger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "date", "category", "name", "amount", "balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLedger.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLedger.setShowHorizontalLines(false);
        tblLedger.getTableHeader().setReorderingAllowed(false);
        tblLedger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLedgerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLedger);
        if (tblLedger.getColumnModel().getColumnCount() > 0) {
            tblLedger.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        rdoShowAll.setLabel("show all");
        rdoShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoShowAllActionPerformed(evt);
            }
        });

        rdoByMonth.setText("by month");
        rdoByMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoByMonthActionPerformed(evt);
            }
        });

        rdoByWeek.setLabel("by week");
        rdoByWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoByWeekActionPerformed(evt);
            }
        });

        btnPrev.setText("<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.setPreferredSize(new java.awt.Dimension(40, 29));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel3.setText("Details");

        jLabel9.setText("--------");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(rdoShowAll)
                            .addComponent(rdoByMonth)
                            .addComponent(rdoByWeek))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoShowAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoByMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoByWeek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        lblForecastDate.setText("2018-03-03");

        jLabel13.setText("... $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrentBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblForecastDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblForecastBal))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblCurrentBal)
                            .addComponent(lblForecastBal)
                            .addComponent(lblForecastDate)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        jLabel5.setText("Amount");

        txtAmount.setToolTipText("Enter the Amount of the transaction");
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        jLabel6.setText("Description");

        txtName.setToolTipText("Enter a name for the item");
        txtName.setMinimumSize(new java.awt.Dimension(150, 26));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "House", "Living", "Debt", "Utilities", "Savings", "Cash", "Auto", "Food", "Unplanned", "Salary", "Transfer", "Insurance", "Open", "Adjustment" }));
        cmbCategory.setSelectedIndex(-1);
        cmbCategory.setToolTipText("");
        cmbCategory.setMinimumSize(new java.awt.Dimension(125, 27));

        jLabel7.setText("Category");

        jLabel8.setText("Date");

        btnAdd.setText("Add");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblMessage.setText("Welcome to fml Finance");
        lblMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtFormatDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yy"))));
        txtFormatDate.setMinimumSize(new java.awt.Dimension(40, 26));

        cbRepeater.setText("Repeat?");
        cbRepeater.setToolTipText("enable repeat entries");

        rdoDelete.setText("delete");
        rdoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDeleteActionPerformed(evt);
            }
        });

        rdoUpdate.setText("update");
        rdoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoUpdateActionPerformed(evt);
            }
        });

        rdoClear.setText("clear");
        rdoClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoClearActionPerformed(evt);
            }
        });

        btnDoIt.setText("Do it");
        btnDoIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoItActionPerformed(evt);
            }
        });

        rdoDeposit.setText("deposit");
        rdoDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDepositActionPerformed(evt);
            }
        });

        rdoExpense.setText("expense");
        rdoExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoExpenseActionPerformed(evt);
            }
        });

        lblDebug.setText("debug label");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rdoDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdoUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDoIt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbRepeater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoDeposit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoExpense)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDebug, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFormatDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoDeposit)
                    .addComponent(rdoExpense)
                    .addComponent(lblDebug))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFormatDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(cbRepeater)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoDelete)
                            .addComponent(rdoUpdate)
                            .addComponent(rdoClear)
                            .addComponent(btnDoIt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analytics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/termaat/Downloads/small-pie-chart.png")); // NOI18N

        jLabel12.setText("starting at");

        jLabel14.setText("ending on");

        lblFirstDay.setText("jLabel15");

        lblLastDay.setText("jLabel15");

        javax.swing.GroupLayout JPanelPieLayout = new javax.swing.GroupLayout(JPanelPie);
        JPanelPie.setLayout(JPanelPieLayout);
        JPanelPieLayout.setHorizontalGroup(
            JPanelPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanelPieLayout.setVerticalGroup(
            JPanelPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFirstDay))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLastDay)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblFirstDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblLastDay))
                .addGap(18, 18, 18)
                .addComponent(JPanelPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         
        //validate the data entry
        String validDE = validateDE();
        
        //if data entry passes then make the update
        if(validDE.equals("FAIL")){
            displayMessage("Data Entry failure. Please validate entry.");
        }
        else{
          // if data entry passed then we will add the transaction
          addTransaction();
          if(rdoShowAll.isSelected()){
            ListTransactions();
            rdoShowAll.setSelected(true);
            rdoByMonth.setSelected(false);
            rdoByWeek.setSelected(false);
          }
          if (rdoByMonth.isSelected()){
              ListTransactions();
              // TO DO
              // Make this retain month view somehow
          }
        }
          
        //check if the repeat is turned on
        if(!cbRepeater.isSelected()){
          clearDE();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!Character.isDigit(vchar)
            || (vchar == KeyEvent.VK_BACKSPACE)
            || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountKeyTyped

    private void tblLedgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLedgerMouseClicked
        //java.util.Date date;
        //String sdate = "";
        
        int i = tblLedger.getSelectedRow();
        row_num = tblLedger.getSelectedRow();
        
        String ids = String.valueOf(model.getValueAt(i, 0));
        int id = Integer.valueOf(ids);
        rec_id = Integer.valueOf(ids);
        
        lblDebug.setText("row: " + String.valueOf(row_num) + 
                " record id: " + rec_id);
        
        String s_amt = String.valueOf(model.getValueAt(i,4));
        int amt = Integer.valueOf(s_amt);
        //if(model.getValueAt(i,4).equals("Deposit")){
        if(amt < 0){
            amt = amt * -1;
            rdoExpense.setSelected(true);
        }
        else{
            rdoDeposit.setSelected(true);
        }
        
        txtAmount.setText(String.valueOf(amt));
        //txtAmount.setText(String.valueOf(model.getValueAt(i, 4)));
        
        txtName.setText(String.valueOf(model.getValueAt(i, 3)));
        
        cmbCategory.setSelectedItem(model.getValueAt(i, 2));
        //cmbCategory.setText(String.valueOf(model.getValueAt(i, 3)));
        
        String ymddate = String.valueOf(model.getValueAt(i, 1));
        String mdydate = FormatDate(ymddate);
        txtFormatDate.setText(mdydate);
    }//GEN-LAST:event_tblLedgerMouseClicked

    private void rdoClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoClearActionPerformed
        if(rdoClear.isSelected()){
            rdoDelete.setSelected(false);
            rdoUpdate.setSelected(false);
        }
    }//GEN-LAST:event_rdoClearActionPerformed
    private void clearDE(){
        txtAmount.setText("");
        txtName.setText("");
        txtFormatDate.setText("");
        cmbCategory.setSelectedIndex(-1);
        rdoClear.setSelected(false);
        rdoDelete.setSelected(false);
        rdoUpdate.setSelected(false);
        rdoDeposit.setSelected(false);
        rdoExpense.setSelected(false);
    }
    
    // takes the date from database and reformats it to something
    // easier to data entry
    private String FormatDate(String ymddate){
        java.util.Date date;
        String mdydate = "";
        
        SimpleDateFormat mdyFormattedDate = new SimpleDateFormat("MM/dd/yy");
        SimpleDateFormat ymdFormattedDate = new SimpleDateFormat("yyyy-MM-dd");
       
        try
        {
          date = ymdFormattedDate.parse(ymddate);
          mdydate = mdyFormattedDate.format(date);          
        }
          catch(ParseException e) {
          displayMessage("Enter date like 04/15/18 " +
                        "and not some other bogus format" +
                        " and not: " + ymddate);
          clearDE();
        }

        return mdydate;
    }
    
    // takes a string date in mdy and returns if that date is 
    // greater than today.  used in balance calculations
    /**
    private String IsDateToday(String mdydate){
        java.util.Date date;
        
        SimpleDateFormat formatDate = new SimpleDateFormat("MM/dd/yy");
        
        try
        {
          date = formatDate.parse(mdydate);
        }
        catch(ParseException e) {
            String error = "ERROR";
            return error;
        }
        
        if(date.after(today)){
            return "GREATER";
        }
        else{
            return"NOTGREATER";
        }
    }
    **/
    
    private void btnDoItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoItActionPerformed
        java.util.Date date;
        int amt = 0;
        int new_amt = 0;
        
        if(rdoClear.isSelected()){
          clearDE();
        }
        if(rdoUpdate.isSelected()){
    
          int amount = Integer.parseInt(txtAmount.getText());
          String name = txtName.getText();
          String category = (String)cmbCategory.getSelectedItem();
          String idate = txtFormatDate.getText();
        
          if (rdoDeposit.isSelected()){}
          else if (rdoExpense.isSelected()){
            amount = amount * -1;}
          else {
              displayMessage("Select Deposit or Expense");
          }
        
          SimpleDateFormat formatDate = new SimpleDateFormat("MM/dd/yy");
        
          try
          {
            date = formatDate.parse(idate);
            sqlDate = new java.sql.Date(date.getTime());
          }
          catch(ParseException e) {
            displayMessage("addTransaction: Enter date like 04/15/18");
            return;
          }     
           
          String ids = String.valueOf(model.getValueAt(row_num, 0));
          int id = Integer.valueOf(ids);
                
            //update the transaction to db
            sqlite.UpdateTran(id, sqlDate, category, name, amount);
            ListTransactions();
            rdoShowAll.setSelected(true);
            rdoByMonth.setSelected(false);
            rdoByWeek.setSelected(false);
            clearDE();
        }
        if (rdoDelete.isSelected()){
          
            //validate the data entry
            String validDE = validateDE();
        
            //if data entry passes then make the update
            if(validDE.equals("FAIL")){
                displayMessage("Data Entry failure. Please validate entry.");
            }
            else{
                //validateDE();
          
                // deal with deposit/expense sign
                if(rdoDeposit.isSelected()){
                    String s_amt = String.valueOf(txtAmount.getText());
                    amt = Integer.valueOf(s_amt);
                    amt = amt * -1;
                }
                else{
                    String s_amt = String.valueOf(txtAmount.getText());
                    amt = Integer.valueOf(s_amt);
                }
        
                
                // do the delete
                // here we need the id to delete
                int i = tblLedger.getSelectedRow();

                String ids = String.valueOf(model.getValueAt(i, 0));
                int id = Integer.valueOf(ids);
            
                sqlite.deleteTran(id);
        
                // if everything went fine
                //displayMessage("Delete selected");
                clearDE();
                ListTransactions();
                rdoShowAll.setSelected(true);
                rdoByMonth.setSelected(false);
                rdoByWeek.setSelected(false);
            }
        }
    
    }//GEN-LAST:event_btnDoItActionPerformed

    private void rdoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDeleteActionPerformed
           if(rdoDelete.isSelected()){
            rdoClear.setSelected(false);
            rdoUpdate.setSelected(false);
        }
    }//GEN-LAST:event_rdoDeleteActionPerformed

    private void rdoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoUpdateActionPerformed
        if(rdoUpdate.isSelected()){
            rdoClear.setSelected(false);
            rdoDelete.setSelected(false);
        }
    }//GEN-LAST:event_rdoUpdateActionPerformed

    private void rdoExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoExpenseActionPerformed
        if(rdoExpense.isShowing()){
            rdoDeposit.setSelected(false);
        }
    }//GEN-LAST:event_rdoExpenseActionPerformed

    private void rdoDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDepositActionPerformed
        if(rdoDeposit.isSelected()){
            rdoExpense.setSelected(false);
        }
    }//GEN-LAST:event_rdoDepositActionPerformed

    // the default selection for ListTransactions whereby everything is shown
    private void rdoShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoShowAllActionPerformed
        rdoByMonth.setSelected(false);
        rdoByWeek.setSelected(false);
        
        this.ListTransactions();;
        
    }//GEN-LAST:event_rdoShowAllActionPerformed
    // show Transactions for the current month only
    private void rdoByMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoByMonthActionPerformed
        rdoShowAll.setSelected(false);
        rdoByWeek.setSelected(false);
        
        //get last day of the current month
        java.sql.Date eomDate = Freaky.getEOM(0);
        
        //get last day of previous month
        java.sql.Date fomDate = Freaky.getFOM(-1);
        
        lblFirstDay.setText("-  " + fomDate);
        lblLastDay.setText(" - " + eomDate);
        
        ListTransactionsNew(fomDate, eomDate);
        
    }//GEN-LAST:event_rdoByMonthActionPerformed
    // show Transactions for the current week
    private void rdoByWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoByWeekActionPerformed
        rdoShowAll.setSelected(false); rdoByMonth.setSelected(false);
        
        java.sql.Date eowDate = Freaky.getEOW(8);
        java.sql.Date fowDate = Freaky.getFOW(8);
        
        //lblFirstDay.setText("-  " + fomDate);
        //lblLastDay.setText(" - " + eowDate);
        
        //int dayofweek = 0;
        
        //get current day
        //Calendar cal = Calendar.getInstance();
        //dayofweek = cal.get(Calendar.DAY_OF_WEEK);

        //we want the last day to be monday of the next week so we can
        //return sunday in the list
        //int lastdaymodifier = 8 - dayofweek;
        
        //add this number to calender to get the last date of the week
        //cal.add(Calendar.DAY_OF_WEEK,  + lastdaymodifier +1);
        
        //java.util.Date lastDateOfWeek = cal.getTime();
        //java.sql.Date sqlDate7 = new java.sql.Date(lastDateOfWeek.getTime());
        //-------------------------
         // to get the previous date we need to subtract  days        
        //int firstdaymodifier = dayofweek - 1;
        
        //cal.add(Calendar.DAY_OF_WEEK,  - 8);
        
        //java.util.Date firstDateOfWeek = cal.getTime();
        //java.sql.Date sqlDate1 = new java.sql.Date(firstDateOfWeek.getTime());
         
        lblFirstDay.setText("-  " + fowDate);
        lblLastDay.setText(" - " + eowDate);
        
        ListTransactionsNew(fowDate, eowDate);
        
    }//GEN-LAST:event_rdoByWeekActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        //move forward a month in transaction list
        if(rdoByMonth.isSelected()){
        
            monTracker++;
            
            //get last day of the current month
            java.sql.Date eomDate = Freaky.getEOM(monTracker);
            
            //get last day of previous month
            java.sql.Date fomDate = Freaky.getFOM(monTracker-1);
            
            lblFirstDay.setText("-  " + fomDate);
            lblLastDay.setText(" - " + eomDate);
        
            ListTransactionsNew(fomDate, eomDate);   
        }
        if (rdoByWeek.isSelected()){
            
            weekTracker = weekTracker+7;
            java.sql.Date eowDate = Freaky.getEOW(weekTracker-1);
            java.sql.Date fowDate = Freaky.getFOW(weekTracker);
            
            lblFirstDay.setText("-  " + fowDate);
            lblLastDay.setText(" - " + eowDate);
            
            ListTransactionsNew(fowDate, eowDate);
            
        }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        
        
        //move forward a month in transaction list
        if(rdoByMonth.isSelected()){
            monTracker--;
        
            //get last day of the current month
            java.sql.Date eomDate = Freaky.getEOM(monTracker);
            //Calendar cal = Calendar.getInstance();
            //cal.set(Calendar.DATE, cal.getActualMaximum(Calendar.DATE));
            //cal.add(Calendar.MONTH, + monTracker);
            //java.util.Date lastDayOfMonth = cal.getTime();
            //java.sql.Date sqlDate30 = new java.sql.Date(lastDayOfMonth.getTime());
        
            //get last day of previous month
            java.sql.Date fomDate = Freaky.getFOM(monTracker-1);
            //Calendar cal1 = Calendar.getInstance();
            //cal1.set(Calendar.DATE, cal1.getActualMaximum(Calendar.DATE));
            //cal1.add(Calendar.MONTH, + (monTracker-1));
            //java.util.Date lastDayOfLastMonth = cal1.getTime();
            //java.sql.Date sqlDate1 = new java.sql.Date(lastDayOfLastMonth.getTime());
        
            lblFirstDay.setText("-  " + fomDate);
            lblLastDay.setText(" - " + eomDate);
            
            ListTransactionsNew(fomDate, eomDate);
        }
        if (rdoByWeek.isSelected()){
            
            weekTracker = weekTracker-7;
            java.sql.Date eowDate = Freaky.getEOW(weekTracker-1);
            java.sql.Date fowDate = Freaky.getFOW(weekTracker);
            
            lblFirstDay.setText("-  " + fowDate);
            lblLastDay.setText(" - " + eowDate);
            ListTransactionsNew(fowDate, eowDate);
            
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmlUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmlUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmlUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmlUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmlUi().setVisible(true);
            }
        });
    }
    
    
    
    private void ListTransactionsNew(Date date1, Date date30){
      String stringDatex = sdf.format(date30.getTime());
      lblForecastDate.setText(stringDatex);
      lblForecastBal.setText(String.valueOf(sqlite.GetBalance(date30)));
      lblCurrentBal.setText(String.valueOf(sqlite.GetBalance(sqlToday)));
     
      //remove all the rows currently in the table
      model.setRowCount(0);
      
      ArrayList<Transaction> ledgerList = sqlite.getTransactionsByDate(date1, date30);
      
      Object rowData[] = new Object[6];
      for(int i = 0; i < ledgerList.size(); i++)
      {
        rowData[0] = ledgerList.get(i).getID();
        rowData[1] = ledgerList.get(i).getDate();
        rowData[2] = ledgerList.get(i).getCategory();
        rowData[3] = ledgerList.get(i).getName();
        rowData[4] = ledgerList.get(i).getAmount();
        rowData[5] = ledgerList.get(i).gettBalance();
        
        model.addRow(rowData);
        
      }    
    }
    
    private void ListTransactions(){
      lblCurrentBal.setText(String.valueOf(sqlite.GetBalance(sqlToday)));
      lblForecastDate.setText(futureDatex);
      lblForecastBal.setText(String.valueOf(sqlite.GetBalance(sqlFutureDate)));
     
      //remove all the rows currently in the table
      model.setRowCount(0);
      
      ArrayList<Transaction> ledgerList = sqlite.getAllObjects();
      Object rowData[] = new Object[6];
      for(int i = 0; i < ledgerList.size(); i++)
      {
        rowData[0] = ledgerList.get(i).getID();
        rowData[1] = ledgerList.get(i).getDate();
        rowData[2] = ledgerList.get(i).getCategory();
        rowData[3] = ledgerList.get(i).getName();
        rowData[4] = ledgerList.get(i).getAmount();
        rowData[5] = ledgerList.get(i).gettBalance();
        
        model.addRow(rowData);
        
      }
      DisplayCatSummary();
    }
    
    private void DisplayCatSummary(){
        
        // get the data from SQlite
        java.sql.Date eomDate = Freaky.getEOM(0);
        java.sql.Date fomDate = Freaky.getFOM(-1);
        ArrayList<CatSummary> catList = sqlite.GetCatSummary(fomDate, eomDate);
        String data[][] = new String[6][2];
        //Object rowData[] = new Object[2];
      for(int i = 0; i < 6; i++){
          for(int j = 0; j < data[i].length; j++){
              data[i][0] = catList.get(i).getCategory();
              int temp = catList.get(i).getAmount();
              data[i][1] = String.valueOf(temp);
          }
          System.out.println(data[i][0] +  " : " + data[i][1]);
      }
              
        // first we need to create a ChartModel object
        //ChartModel pie = new ChartModel();
        
        //now we need to pop up the chart with test data
        //final TableChartPopup tcp = new TableChartPopup(pie.tm); 
        //JPanelPie.add(tcp.GetPieChart());
        //JPanelPie.setVisible(true);
        
    }
    
    // this method validates the DE part of the form and 
    // returns PASS or FAIL to caller
    private String validateDE(){
        if(txtAmount.getText().equals("")){
            return "FAIL";}
        else if(txtName.getText().equals("")){
            return "FAIL";}
        else if(cmbCategory.getSelectedIndex() == -1){
            return "FAIL";
        } else if(!(rdoDeposit.isSelected() || rdoExpense.isSelected())){
            return "FAIL";
        } else {
            return "PASS";}
        
    }
    
    /**
    private void AddFirstTransaction(){
        java.util.Date date;
    
          int amount = Integer.parseInt(txtAmount.getText());
          String name = txtName.getText();
          String category = (String)cmbCategory.getSelectedItem();
          String idate = txtFormatDate.getText();
        
          if (rdoDeposit.isSelected()){}
          else if (rdoExpense.isSelected()){
            amount = amount * -1;}
          else {
              displayMessage("Select Deposit or Expense");
          }
        
          SimpleDateFormat formatDate = new SimpleDateFormat("MM/dd/yy");
        
          try
          {
            date = formatDate.parse(idate);
            sqlDate = new java.sql.Date(date.getTime());
          }
          catch(ParseException e) {
            displayMessage("addTransaction: Enter date like 04/15/18");
            return;
          }
          
            //add the transaction to db
            lstInsertID = sqlite.insertTran(sqlDate, category, name, amount);
            ListTransactions();
    }
    **/
    
    private void addTransaction(){
    java.util.Date date;
    
          int amount = Integer.parseInt(txtAmount.getText());
          String name = txtName.getText();
          String category = (String)cmbCategory.getSelectedItem();
          String idate = txtFormatDate.getText();
        
          if (rdoDeposit.isSelected()){}
          else if (rdoExpense.isSelected()){
            amount = amount * -1;}
          else {
              displayMessage("Select Deposit or Expense");
          }
        
          SimpleDateFormat formatDate = new SimpleDateFormat("MM/dd/yy");
        
          try
          {
            date = formatDate.parse(idate);
            sqlDate = new java.sql.Date(date.getTime());
          }
          catch(ParseException e) {
            displayMessage("addTransaction: Enter date like 04/15/18");
            return;
          }
        
            //add the transaction to db
            lstInsertID = sqlite.insertTran(sqlDate, category, name, amount);
            ListTransactions();
            rdoShowAll.setSelected(true);
            rdoByMonth.setSelected(false);
            rdoByWeek.setSelected(false);
    }
    private void displayMessage(String message){
        lblMessage.setText(message);
        
        Timer t = new Timer(1500, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                lblMessage.setText(null);
            }
        });
        t.setRepeats(false);
        t.start();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelPie;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDoIt;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbRepeater;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCurrentBal;
    private javax.swing.JLabel lblDebug;
    private javax.swing.JLabel lblFirstDay;
    private javax.swing.JLabel lblForecastBal;
    private javax.swing.JLabel lblForecastDate;
    private javax.swing.JLabel lblLastDay;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JRadioButton rdoByMonth;
    private javax.swing.JRadioButton rdoByWeek;
    private javax.swing.JRadioButton rdoClear;
    private javax.swing.JRadioButton rdoDelete;
    private javax.swing.JRadioButton rdoDeposit;
    private javax.swing.JRadioButton rdoExpense;
    private javax.swing.JRadioButton rdoShowAll;
    private javax.swing.JRadioButton rdoUpdate;
    private javax.swing.JTable tblLedger;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JFormattedTextField txtFormatDate;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
